-- jack
owner.Character.Humanoid.DisplayName = [==[TOTALLY REAL NOT FAKE NOT IMPOSTER ]==]..owner.Name..[==[  (CHAD, MONSTER SIDE, POWER OF 1000 BLOOD MOONS, SON OF ZEUS, BAD GUY, SMOKES, IS OWNER OF MRBEAST(DOG, ALSO REAL MRBEAST),
 DEFEATED TECHNOBLADE MATH.HUGE TIMES, HALF ANKLE, HALF DEMON, SINGEL,
JACK(]==]..owner.Name..[==[),DOESN'T KNOW ANYONE,NEW KID AT SCHOOL,
 HOT, PLAYED ROBLOX SINCE 1999 IS GOD, ORPHAN AT THE AGE OF 0, MET JESUS, BETTER THAN YOU ON ANY GAME, BULLY, BULLIED SINCE 69 YEARS, 
EVIL SIDE KILLS, GOOD SIDE DIED, HAS 9999999999999999999 FANS, NEVER DIES, NEEDS A MOTHER, 3 YEARS OLD, 
VAMPIRE, CREATED PROGRAMMING, JOE IS BFF, FLAMINKO, NEVER DIED IN A GAME, NOT TOXIC, JAKE IS BFF 100%, 
MADE A DEAL WITH THE DEVIL FOR 10 VBUCK, DID A BACKFLIP AND SNAPPED THE BAD
GUYS NECK, EW_001S ONE AND ONLY CREATOR, CREATED ROBLOX, IS ROBLOX, BLOCKS YOUR DODGE,
YOU CANT SEE ME, CREATED THE MULTIVERSE, IS SPIDERMAN, WAS IN SPIDERMAN: NO WAY I'M HOMELESS]==]
-- UP TO DATE.