-- tutorial
print("Please read the tutorial carefully as it will type in slowly for you.")
wait(4)
print("To create a script type in chat or in output 'create/scriptname'")
wait(3)
print("To edit a script type in chat or in output 'edit/scriptname'")
wait(4)
print("To exit edit mode type in chat or in output 'exit/' while editing.")
wait(6)
print("To clear a script while in edit mode type in chat or in output 'clear/'")
wait(7)
print("To remove a script type in chat or in output 'remove/scriptname'")
wait(4)
print("To save a script type in chat or in output 'save/scriptname' (will save the script to next time you join it will still be there)")
wait(10)
print("To create a script and insert the source directly type in chat or in output 'cs/scriptname/source'")
wait(7)
print("To rename a script type in chat or in output 'rename/scriptname/newname'")
wait(6)
print("To run a script type in chat or in output 'r/scriptname'")
wait(4)
print("To run a script on your client type in chat or in output 'rl/scriptname'")
wait(6)
print("To run a script link type in chat or in output 'h/yourlink'")
wait(5)
print("To run a script link on your client type in chat or in output 'hl/yourlink'")
wait(6)
print("Thats the end of the tutorial, hope it helped you.")
-- UP TO DATE.